// import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header'
import AppTable from '@/components/app.table'
import AppFooter from '@/components/app.footer'
import Container from 'react-bootstrap/Container'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer,toast } from 'react-toastify'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// children layout động
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Container>
         <AppHeader/>
         {children}
         <AppFooter/> 
         </Container>
         <ToastContainer />
      </body>
    </html>
  )
}
